export const FETCH_PATIENTS = 'FETCH_PATIENTS';
export const FETCH_PATIENT = 'FETCH_PATIENT';
export const CREATE_PATIENT = 'CREATE_PATIENT';
export const EDIT_PATIENT = 'EDIT_PATIENT';
export const DELETE_PATIENT = 'DELETE_PATIENT';
